### ISSUE TITLE
compiled.py/test.blend update to export .ogex instead of .dae

### ISSUE THREAD

**Issue by Devination** [luboslenco/zblend_blender#3]
Hi Lubos,

Super excited about this project, been watching the progress on your twitter and haxe.io. Like Nananas, I'm also a windows user and ran into the same issues he did. The bash commands from Blender never seemed to run for me, all the other parts of the script did though. I ended up writing a .bat file with hardcoded paths to make it build.

Once it built, I noticed that it spit out a .dae file and the Main.hx file still had "import fox.trait.DaeScene;" in it instead of "GameScene". Looking at compiled.py, it looks like lines 318, 333, and 438 are still referencing collada rather than opengex.

Good work on Fox so far, it's awesome to see it progress so much so fast! Happy new year :)

**Comment by luboslenco** [comment]
Hello Devination,

Had no idea anyone would be watching, thanks for interest. If you update everything Fetch and Build buttons should work on Windows, however Run and Project buttons are not yet imlemented so you need to manually open exported Visual Studio project. Also replaced collada references with opengex, so it should actually build.

Wish the same to you! :)

**Comment by Devination** [comment]
Thanks for the Update! The Fetch and Build buttons in Blender do indeed work now however I cannot get the builds to run D:

For HTML5: When trying to load the .html file directly I get an error "loadBlob failed". If I try to run from FlashDevelop using the generated .hxproj I get no error, just the blue loading bar that fills but nothing else happens.

For Windows: When I open up the generated .vcxproj in Visual Studio and try to build I get this error:

"Error	1255	error C2124: divide or mod by zero	c:\users\upgraded\documents\git\foxtest\build\windows-build\sources\src\oimo\physics\collision\narrowphase\boxboxcollisiondetector.cpp	33	1	test"

**Comment by Nananas** [comment]
Just wanted to say that I got the exact same errors.

I solved the HTML5 one by serving the html5 folder on localhost with python, because Chrome (and others) does not allow to open local files: 
```
Python3> python -m http.server
Python2> python -m SimpleHTTPServer
```
and then browsing to `localhost:8000`

But after this I get the following error (Chrome console):
```
Uncaught RangeError: Invalid typed array length    |    kha.js:11964
   kha.LocalStorageFile.decode                     |    kha.js:11978
   ...
```

**Comment by luboslenco** [comment]
Robert told me there were some changes in Haxe so storage got broken. I disabled it in the latest commit and HTML5 should really work now(hopefully).

https://ee5acec1342ebd4ab2c35152284d29b302681115.googledrive.com/host/0B22ElR_OUmfdYktqMmZ4NmI5ZzQ/index.html

As Nananas said it still can not run locally though. You can also serve it from Dropbox/Google Drive/etc., but having a local server should be more efficient.

Got the same errors on Windows, funny that it works on OS X. Will check it out.

**Comment by Nananas** [comment]
Yep, it's working. :+1:
