### ISSUE TITLE
Collections with the same name act as if only one

### ISSUE THREAD

**Issue by Nananas** [luboslenco/zblend_blender#6]
When making a second collection with the same name as an already existing collection, the second collection gets assigned to the object, but the traits of the *first* collection are shown instead.

An example:
- Make a cube and assign a new collection called `Cube` to it
- add a mesh renderer to this collection
- Make a new collection, also called `Cube`
- switching between the two `Cube` collections will still show the mesh renderer in the traits list
- note that the result is different when built: the object with the second `Cube` collection is invisible, as it has no mesh renderer assigned

Probably caused by taking the first matching element in the [list](https://github.com/luboslenco/fox_blender/blob/b6b3de0842fe5882d482e347cdad3783ff948fe1/fox_traits.py#L244).

And some beautiful images cause why not :trollface: :
![Invisible](https://dl.dropboxusercontent.com/u/29991430/Fox_issueCollectionsDuplicate_invisible.PNG)
![Visible](https://dl.dropboxusercontent.com/u/29991430/Fox_issueCollectionsDuplicate_visible.PNG)

**Comment by luboslenco** [comment]
Pushed update to force unique collection name. If a collection with the same name gets created, the old one is renamed - similar to Blender naming.

Woot! Looks interesting! :+1:
