### ISSUE TITLE
Process also spawns a Blender instance

### ISSUE THREAD

**Issue by Nananas** [luboslenco/zblend_blender#7]
The following lines spawn a blender.exe instead of a python process. So this opens a new Blender instance. :astonished:
```python
 p = Process(target=run_server)
 p.start()
```

This apparently only happens on a Windows.

A possible solution might be to get the system-installed python distribution. But there might not be one... I only tested for bugs. It could be that it actually does not work properly :innocent: :
```python
# get the local python distribution
local_python_path = subprocess.check_output("where python").decode("utf-8").strip()
multiprocessing.set_executable(local_python_path) 
p = Process(target=run_server)
p.start()
```

Note that an operating system check is needed first, as `where` is a Windows command afaik.

**Comment by luboslenco** [comment]
Thanks for notice!

Hm I still couldn't get it to work on my machine, seems like multiprocessing is troubling on Windows. This would also require another dependency to have installed as you said.

Will try to figure out some other way..

**Comment by Nananas** [comment]
Can't you use `node.js` to host a local webserver? Or is `node.js` not a dependency anymore?

**Comment by luboslenco** [comment]
Should be fixed now - found a way to start Blender with no UI so it acts like a python interpreter.

This could also open up new possibilities as it can fully operate on project data in separate Blender instance.

**Comment by Nananas** [comment]
Alright! Looks good.
It tries to open `127.0.0.1:8000/...` and not `http://127.0.0.1:8000/...`. As such, I get a little popup saying `no program installed to open this type of link`. Adding the `http://` in front should solve it.
